services:
  # Redis + Redis Insight
  redis:
    image: redis:7.4.1
    container_name: redis
    restart: always
    volumes:
      - ecommerce_graybee_redis_volume:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - .env
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    networks:
      - graybee
  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redisInsight
    restart: always
    ports:
      - "5000:8001"
    volumes:
      - ecommerce_graybee_redisInsight_volume:/db
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - graybee

  # MySQL
  mysql:
    image: mysql:8.0.40
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ecommerce_graybee_mysql_volume:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - graybee

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.15.0
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ecommerce_graybee_elasticsearch_volume:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
      test: [ "CMD", "curl", "-s", "-f", "http://localhost:9200/_cluster/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - graybee

  kibana:
    container_name: kibana
    image: kibana:8.15.0
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - graybee

  # Spring Boot App
  graybee:
    build:
      context: .
      dockerfile: dockerfile
    image: ecommerce_graybee_server
    container_name: ecommerce_graybee_server
    ports:
      - 8080:8080
    environment:
      - MYSQL_HOST=${MYSQL_HOST_DOCKER}
      - REDIS_HOST=${REDIS_HOST_DOCKER}
      - ELS_HOST=${ELS_HOST_DOCKER}
    env_file:
      - .env
    networks:
      - graybee
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy


networks:
  graybee:
    driver: bridge
    external: true

volumes:
  ecommerce_graybee_redis_volume:
    external: true
  ecommerce_graybee_redisInsight_volume:
    external: true
  ecommerce_graybee_mysql_volume:
    external: true
  ecommerce_graybee_elasticsearch_volume:
    external: true


