spring:
  application:
    name: Ecommerce-Graybee
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=true&serverTimezone=Asia/Ho_Chi_Minh
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 20
          order_insert: true
          order_update: true
  output:
    ansi:
      enabled: always
  cache:
    type: redis
  data:
    redis:
      repositories:
        enabled: false
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE}
    elasticsearch:
      repositories:
        enabled: false
      uris: http://localhost:9200
#      username: elastic
#      password: admin123

server:
  address: 0.0.0.0
  port: 8080

servlet:
  multipart:
    enabled: true
    max-file-size: 10MB
    max-request-size: 10MB

logging:
  level:
    com:
      zaxxer: ERROR

api:
  admin: /api/v1/admin
  categories: ${api.admin}/categories
  manufacturers: ${api.admin}/manufacturers
  products: ${api.admin}/products
  orders: ${api.admin}/orders
  tags: ${api.admin}/tags
  subcategories: ${api.admin}/subcategories


jwt:
  secretKey: ${SECRET_KEY}
  expiration: ${EXPIRATION}
  header: ${HEADER}
  prefix: ${PREFIX}