spring:
  application:
    name: Ecommerce-Graybee
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${MYSQL_SOURCE}${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=true&serverTimezone=Asia/Ho_Chi_Minh
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 20
          order_insert: true
          order_update: true
  output:
    ansi:
      enabled: always
  cache:
    type: redis
  data:
    redis:
      repositories:
        enabled: false
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE}
    elasticsearch:
      repositories:
        enabled: false
      host: ${ELS_HOST}
      username: ${ELS_USERNAME}
      password: ${ELS_PASSWORD}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  address: 0.0.0.0
  port: ${PORT:8080}

servlet:
  multipart:
    enabled: true
    max-file-size: 10MB
    max-request-size: 10MB

logging:
  level:
    org.springframework.security: DEBUG
    com:
      zaxxer: ERROR

api:
  version: v1
  base-path: /api/${api.version}
  admin:
    base-path: ${api.base-path}/admin
    dashboard: ${api.admin.base-path}/dashboard
    categories: ${api.admin.base-path}/categories
    attributes: ${api.admin.base-path}/attributes
    products: ${api.admin.base-path}/products
    inventories: ${api.admin.base-path}/inventories
    permissions: ${api.admin.base-path}/permissions
    orders: ${api.admin.base-path}/orders
    deliveries: ${api.admin.base-path}/deliveries
    payments: ${api.admin.base-path}/payments
    accounts: ${api.admin.base-path}/accounts
    customers: ${api.admin.base-path}/customers
    image-kit: ${api.admin.base-path}/image-kit
    cloudinary: ${api.admin.base-path}/cloudinary
  home: ${api.base-path}/home
  products: ${api.base-path}/products
  collections: ${api.base-path}/collections
  carts: ${api.base-path}/carts
  auth: ${api.base-path}/auth
  orders: ${api.base-path}/orders
  account: ${api.base-path}/account

jwt:
  secretKey: ${SECRET_KEY}
  expiration: ${EXPIRATION}
  header: ${HEADER}
  prefix: ${PREFIX}

origin:
  techstore: ${TECHSTORE}
  techstoreDashboard: ${TECHSTORE_DASHBOARD}